name: smileyHorizon
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - async-timeout=5.0.1
  - attrs=25.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.21.0
  - aws-c-mqtt=0.13.1
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - contourpy=1.3.1
  - cpython=3.10.18
  - cycler=0.11.0
  - datasets=3.6.0
  - dill=0.3.8
  - emoji=2.14.1
  - filelock=3.18.0
  - fonttools=4.55.3
  - freetype=2.13.3
  - frozenlist=1.7.0
  - fsspec=2025.3.0
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - googletrans=2.4.0
  - h2=4.2.0
  - hdbscan=0.8.39
  - hf-xet=1.1.6
  - hpack=4.1.0
  - huggingface_hub=0.34.3
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - jinja2=3.1.6
  - joblib=1.5.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libarrow=20.0.0
  - libarrow-acero=20.0.0
  - libarrow-dataset=20.0.0
  - libarrow-substrait=20.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libcxx=20.1.8
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.71.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.64.0
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=20.0.0
  - libpng=1.6.50
  - libprotobuf=5.29.3
  - libre2-11=2025.06.26
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.7.1
  - libutf8proc=2.10.0
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - llvmlite=0.44.0
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mkl=2023.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.6.3
  - multiprocess=0.70.16
  - narwhals=2.0.1
  - ncurses=6.5
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - numba=0.61.2
  - numpy=2.2.6
  - openjpeg=2.5.3
  - openssl=3.5.2
  - optree=0.17.0
  - orc=2.1.2
  - packaging=25.0
  - pandas=2.3.1
  - pillow=11.3.0
  - pip=25.1
  - plotly=6.2.0
  - prometheus-cpp=1.3.0
  - propcache=0.3.1
  - pthread-stubs=0.4
  - pyarrow=20.0.0
  - pyarrow-core=20.0.0
  - pybind11=3.0.0
  - pybind11-global=3.0.0
  - pycparser=2.22
  - pynndescent=0.5.13
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-gil=3.10.18
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.7.1
  - pytz=2025.2
  - pyyaml=6.0.2
  - re2=2025.06.26
  - readline=8.2
  - regex=2025.7.34
  - requests=2.32.4
  - safetensors=0.5.3
  - scikit-learn=1.7.1
  - scipy=1.15.2
  - sentence-transformers=5.0.0
  - setuptools=78.1.1
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.2
  - sqlite=3.50.4
  - sympy=1.14.0
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tokenizers=0.21.4
  - tornado=6.5.1
  - tqdm=4.67.1
  - transformers=4.55.0
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - umap-learn=0.5.9.post2
  - unicodedata2=15.1.0
  - urllib3=2.5.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.3
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.1
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
prefix: /Users/nlengineer/miniconda3/envs/smileyHorizon
