name: smileyHorizon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      - googletrans
      - emoji
      - sentence-transformers
      - umap-learn
      - hdbscan
      - plotly